Add virtual truck control plugin
robotics-laboratory/foxglove pull request #3
Opened 2023-08-05 01:57 UTC by tane-superior

2023-08-05 21:22 UTC, AndBondStyle requested changes

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +import {create, JoystickManager, JoystickManagerOptions, Position} from 'nipplejs';
Эта зависимость уже есть в package.json?

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +    auto: 2,
Как-то получается, что плагин очень сильно заточен под конкретную задачу, но в то же время сообщения посылает, как будто это просто джойстик. Я бы сказал что нужно один из двух стульев выбрать (либо выбрать оба и уметь между ними переключаться):
1. Честно симулируем все возможности джойстика (в разумных пределах). И никаких упоминаний "truck", "remote", "auto" быть не должно, т.к. плагин абсолютно generic и не привязан к конкретному проекту
2. Абстрагируемся от конкретного проекта, но сохраняем общим концепции, типа "можем ехать влево, вправо, вперёд, назад. Переключаться между режимами off, remote, auto". Чтобы это работало, нужно будет ещё переделать control proxy и желательно тоже его от конкретного проекта, чтобы его можно было переиспользовать на разных роботах. Уже давно крутится эта идея, попробую в ближайшее время накидать proposal, как я себе это представляю

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +  let nigger = new Date();
Bruh

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +    setInterval(() => publish(), publishRate);
Не уверен, но кажется в реакте так делать это бан

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +const publishRate = 300;
Зашито  (+ это очень много, на самом деле)

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/TruckControlPanel.tsx
> +    frame_id: string,
А вот это как раз странно в настройки выводить, потому что для джойстика фрейм вроде бы не имеет смысла

2023-08-05 21:22 UTC, AndBondStyle commented on extensions/src/index.ts
> +import { initTruckControlPanel } from "./TruckControlPanel";
Если решим, что плагин все-таки generic, то надо будет переназвать без использования truck (например JoystickPanel)

2023-08-05 21:25 UTC, tane-superior commented on extensions/src/TruckControlPanel.tsx
> +  let nigger = new Date();
думал, что дочистил, оказалось, нет

2024-02-18 06:31 UTC, AndBondStyle commented
Superseded by #6

2024-02-18 06:31 UTC, closed without merging